version: 2 

models:
  - name: customers 
    description: Cleaned up data of our customers 
    columns:
      - name: customer_id
        description: Primary key of the model
        tests:
          - unique 
          - not_null
      - name: name 
        description: First and last name of customer 
      - name: email 
        description: Email of customers
      - name: number_of_orders 
        description: The total number of orders placed by the customer 
      - name: first_order_at
        description: The date of the first order placed of the customer 
      - name: last_order_at
        description: The date of the last order placed of customer. Will be the same as first_order_at if they have only placed 1 order.
      - name: customer_type
        description: New or Returned. If number of orders = 1 then new, if number of orders > 1 then returned. 

  - name: monthly_customers 
    description: The number of monthly customers who have placed and order
    columns:
      - name: signup_month 
        description: The month of a customers first order 
        tests:
          - not_null
          