version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: products 
        columns:
          - name: id 
            tests:
              - unique
              - not_null 

      - name: product_prices 
        columns:
          - name: id 
            tests:
              - unique 
              - not_null 
      
      - name: order_items 
        columns: 
          - name: id 
            tests: 
              - unique 
              - not_null

  - name: web_tracking
    project: analytics-engineers-club
    tables:
      - name: pageviews 

  - name: advanced_dbt_examples
    project: analytics-engineers-club
    tables:
      - name: form_events

      

            